flags: {}
extra-package-dbs: []
packages:
- location: '.'
- location:
    git: git@github.com:wamaral/slack-api.git
    commit: 9c5fffec88723a51099ed77bf80858817596c717
extra-deps:
- datetime-0.3.1
- wreq-0.5.0.0
resolver: lts-8.0
