flags: {}
extra-package-dbs: []
packages:
- location: '.'
- location:
    git: git@github.com:wamaral/slack-api.git
    commit: 15f0acb607e67e43670f0f5d5c73eb5b47556be7
extra-deps:
- datetime-0.3.1
- wreq-0.5.0.0
resolver: lts-8.0
